const topAO3Fandoms = [
	// Anime/Manga
	'My Hero Academia',
	'Attack on Titan',
	'Haikyuu!!',
	'Jujutsu Kaisen',
	'Demon Slayer',
	'One Piece',
	'Solo Leveling',
	'Naruto',
	'Bungou Stray Dogs',
	'Tokyo Revengers',
	'Yuri!!! on Ice',
	'Free!',
	"JoJo's Bizarre Adventure",
	'Black Butler',
	'Fruits Basket',
	'Sk8 the Infinity',
	'Given',
	'Blue Lock',
	'Chainsaw Man',
	'Spy x Family',

	// Books/Literature
	'Harry Potter',
	'Percy Jackson',
	'The Hunger Games',
	'A Song of Ice and Fire',
	'Twilight',
	'Shadowhunters',
	'The Witcher',
	'Good Omens',
	'Sherlock Holmes',
	'The Locked Tomb Series',
	'Six of Crows',
	'The Magnus Archives',
	'Dungeons & Dragons',
	'The Sandman',
	'Discworld',
	'The Raven Cycle',
	'Red White & Royal Blue',
	'Heartstopper',
	'They Both Die at the End',
	'The Cruel Prince',

	// TV/Film
	'Stranger Things',
	'Supernatural',
	'MCU',
	'Star Wars',
	'Doctor Who',
	'Merlin',
	'The Untamed',
	'Guardian',
	'Star Trek',
	'The Mandalorian',
	'Loki',
	'Good Omens',
	'Our Flag Means Death',
	'What We Do in the Shadows',
	'The Last of Us',
	'House of the Dragon',
	'The Umbrella Academy',
	'Bridgerton',
	'The Owl House',
	'She-Ra and the Princesses of Power',

	// Video Games
	"Baldur's Gate III",
	'Genshin Impact',
	'The Legend of Zelda',
	'Final Fantasy',
	'Honkai: Star Rail',
	'Honkai Impact 3rd',
	'Fire Emblem',
	'Overwatch',
	'Mass Effect',
	'Dragon Age',
	'Cyberpunk 2077',
	'Stardew Valley',
	'Undertale',
	'Hades',
	'Portal',
	'Bioshock',
	'The Last of Us',
	'Red Dead Redemption',
	'Elden Ring',
	'Persona 5',

	// K-Pop
	'BTS',
	'SEVENTEEN',
	'Stray Kids',
	'TOMORROW X TOGETHER',
	'ATEEZ',
	'ENHYPEN',
	'NCT',
	'EXO',
	'SHINee',
	'BLACKPINK',
	'TWICE',
	'Red Velvet',
	'LE SSERAFIM',
	'NewJeans',
	'IVE',
	'aespa',
	'ITZY',
	'Dreamcatcher',
	'MAMAMOO',
	'GOT7',

	// Other
	'K-pop RPF',
	'YouTube RPF',
	'Podcasts',
	'Critical Role',
	'Dimension 20',
	'Welcome to Night Vale',
	'The Adventure Zone',
	'Dream SMP',
	'Hermitcraft',
	'Homestuck',
	'Warrior Cats',
	'Warhammer 40k',
	'Original Work',
	'No Fandom',
	'Bandfic',
	'Hamilton',
	'Dear Evan Hansen',
	'Heathers',
	'Be More Chill'
];
