export const topAO3Tags = [
	// Genre/Content Tags
	'Fluff',
	'Angst',
	'Hurt/Comfort',
	'Alternate Universe',
	'Canon Compliant',
	'Domestic Fluff',
	'First Time',
	'Mutual Pining',
	'Slow Burn',
	'Post-Canon',
	'Graphic Depictions of Violence',
	'Crack Treated Seriously',
	'Time Travel',
	'Alternate Universe - Modern Setting',
	'Fix-It',
	'Character Study',
	'Arranged Marriage',
	'Kidnapping',
	'Unrequited Love',
	'Friends to Lovers',
	'Enemies to Lovers',
	'Soulmates',
	'Smut',
	'Romance',
	'Drama',
	'Humor',
	'Dark',
	'Emotional Hurt',
	'Fluff and Angst',
	'Tragedy',

	// Relationship Dynamics
	'Friendship',
	'Found Family',
	'Romantic Fluff',
	'Sexual Tension',
	'Unhealthy Relationships',
	'Co-Parenting',
	'Rivals to Lovers',
	'Sibling Bonding',
	'Team as Family',
	'Emotional Support',
	'Miscommunication',
	'Jealousy',
	'Possessive Behavior',
	'Sharing a Bed',
	'Mutual Attraction',
	'Secret Relationship',
	'Forced Proximity',
	'Love Confessions',
	'Marriage Proposal',
	'Wedding',

	// Specific Tropes
	'Coffee Shop AU',
	'College AU',
	'Supernatural Elements',
	'Magic Realism',
	'Fake Dating',
	'Only One Bed',
	'Hanahaki Disease',
	'Omegaverse',
	'Time Loop',
	'Amnesia',
	'Identity Porn',
	'Body Swap',
	'Mutual Pining',
	'Angst with a Happy Ending',
	'Hurt/Comfort with a Happy Ending',
	'Major Character Death',
	'Temporary Character Death',
	'Resurrection',
	'Ghosts',
	'Vampires',
	'Werewolves',
	'Cyberpunk',
	'Space Opera',

	// Content Warnings/Notes
	'No Beta We Die Like Men',
	'Creator Chose Not To Use Archive Warnings',
	'Not Actually Unrequited Love',
	'Happy Ending',
	'Bittersweet Ending',
	'Ambiguous Ending',
	'Open Ending',
	'Tragic Ending',
	'Dark Ending',
	'Implied/Referenced Abuse',
	'Mental Health Issues',
	'Recovery Arc',
	'Healing',
	'Trauma',
	'PTSD',
	'Nightmares',
	'Panic Attacks',
	'Substance Abuse',
	'Eating Disorders',
	'Self-Harm',

	// Format/Style
	'POV Alternating',
	'Epistolary',
	'Poetry',
	'Drabble Collection',
	'Songfic',
	'Chatfic',
	'Textfic',
	'Social Media AU',
	'Podfic',
	'Fanvid',
	'Art Insert',
	'Interactive Fiction',
	'Choose Your Own Adventure'
];
